name: Fetch and Convert Files

on:
  # 当 Process and Fetch Rule 工作流执行完成后触发
  workflow_run:
    workflows: ["Process and Fetch Rule"]
    types:
      - completed
  # 每天 UTC 时间 20:00 触发（北京时间 04:00）
  schedule:
    - cron: '0 20 * * *'
  # 当 script 文件夹下的 json 文件有更新时触发
  push:
    paths:
      - 'script/*.json'
  # 手动触发
  workflow_dispatch: 

jobs:
  fetch_and_convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyyaml requests
    
    # 运行 fetch_and_convert.py 脚本
    - name: Run fetch and convert script
      run: |
        python script/fetch_and_convert.py

    # 提交推送
    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.PUSH_EVERYDAY }}
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        if git diff-index --quiet HEAD; then
          echo "没有文件更改，跳过提交。"
        else
          git commit -m "Auto-fetched and converted files to YAML"
          git pull origin main --rebase
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git
          if git push origin main; then
            echo "推送成功。"
          else
            echo "推送失败，请检查远程分支是否有冲突。"
            exit 1
          fi
        fi