name: Fetch and Convert Files

on:
  push:
    # 当main分支提交时,自动运行当前action
    branches:
      - main
  schedule:
    # 每日更新
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  fetch_and_convert:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # 安装Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # 更新pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyyaml requests
    
    # 运行fetch_and_convert.py脚本
    - name: Run fetch and convert script
      run: |
        python .github/workflows/fetch_and_convert.py

    # 提交推送
    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.PUSH_EVERYDAY }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Auto-fetched and converted files to YAML" || git diff-index --quiet HEAD
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git push origin main || echo "No changes to push"