name: Process and Fetch Rules

on:
  # 原始触发条件：当 user_rule 文件夹下有更新时触发
  push:
    paths:
      - 'user_rule/**'
  # 手动触发
  workflow_dispatch:
  # 当 Process JSON URLs 工作流成功完成后触发
  workflow_run:
    workflows: ["Process JSON URLs"]
    types:
      - completed

jobs:
  process_rule:
    runs-on: ubuntu-latest

    # 仅在原始触发条件满足时运行
    if: |
      github.event_name == 'push' && contains(github.event.commit.modified.*.startsWith('user_rule/'), true) ||
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event_name == 'push' && contains(github.event.commit.modified.*.startsWith('user_rule/'), true))
    
    outputs:
      has_changes: ${{ steps.check-changes.outputs.has_changes }}  # 将 has_changes 作为作业输出
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check for changes in user_rule directory
      id: check-changes
      run: |
        # 检查 user_rule 目录是否有更改
        if git diff --quiet HEAD^ HEAD -- user_rule; then
          echo "No changes in user_rule directory."
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected in user_rule directory."
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Set up Python
      if: steps.check-changes.outputs.has_changes == 'true'
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 运行 process_rule.py 脚本
    - name: Run Process Rule Python script
      if: steps.check-changes.outputs.has_changes == 'true'
      run: |
        python3 script/process_rule.py

    - name: Commit processed rule changes
      env:
        GH_TOKEN: ${{ secrets.PUSH_EVERYDAY }}
      if: steps.check-changes.outputs.has_changes == 'true'
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        if git diff-index --quiet HEAD; then
          echo "没有文件更改，跳过提交。"
        else
          git commit -m "Processed rule files with total rules count and sorted rules"
          git pull origin main --rebase
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git
          if git push origin main; then
            echo "推送成功。"
          else
            echo "推送失败，请检查远程分支是否有冲突。"
            exit 1
          fi
        fi