name: Process JSON URLs

on:
  # 当 script 文件夹下的 json 文件有更新时触发
  push:
    paths:
      - 'script/**/*.json'
  # 手动触发
  workflow_dispatch:

jobs:
  process-urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Process JSON files
        run: |
          # 遍历 script/ 文件夹下的所有 .json 文件
          for file in script/*.json; do
            echo "Processing file: $file"

            # 使用 jq 修改 rules_urls 中的 URL
            jq '.[].rules_urls |= map(gsub("/refs/heads/"; "/"))' "$file" > "$file.tmp"
            mv "$file.tmp" "$file"

            echo "Updated file: $file"
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Automatically remove refs/heads/ from URLs in JSON files"
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git push origin main